# Generated by Django 3.2.16 on 2023-04-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_wallet_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount_currency',
            field=models.CharField(choices=[('RUB', 'Rub'), ('KZT', 'Kzt'), ('USD', 'Usd')], default='KZT', max_length=3),
        ),
    ]
